// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace RapidMountain.Persistence.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NameFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201610272200084_NameFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
