// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace RapidMountain.Persistence.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CartSecondKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CartSecondKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201611160135005_CartSecondKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
